name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:       # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to allow pushing to the repo

    steps:
      # Checkout the output branch (or create it if it doesn't exist)
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output  # 👈 checkout the `output` branch
          persist-credentials: false  # avoids issues with PAT vs token

      # Generate the snake animations
      - uses: Platane/snk@master
        with:
          github_user_name: KaranVenkatesan
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
          color_snake: '#0D1117'
          color_dots: '#58A6FF'
          color_eyes: '#58A6FF'

      # Push the generated SVGs to the output branch
      - name: Push snake animation to output branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/
          git commit -m "Update snake animation [skip ci]" || echo "No changes to commit"
          git push origin output  # 👈 ensure this pushes to output branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
