name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      # Generate both light and dark snakes
      - uses: Platane/snk@master
        id: snake-light
        with:
          github_user_name: KaranVenkatesan
          svg_out_path: dist/github-snake.svg
          
      - uses: Platane/snk@master
        id: snake-dark
        with:
          github_user_name: KaranVenkatesan
          svg_out_path: dist/github-snake-dark.svg
          color_snake: '#0D1117'
          color_dots: '#58A6FF'
          color_eyes: '#58A6FF'

      # Push to your main branch
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/
          git commit -m "Update snake animation [skip ci]"
          git push
